import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import News from '@/components/News'
import MobileFooter from '@/components/MobileFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Football info',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='px-2 md:px-12 md:py-2 text-textPrimary flex flex-col'>
          <Navbar />
          {/* Main Content */}
          <section className='flex flex-1 space-x-4'>
            {/* Sidebar on desktop only */}
            <div className="hidden lgplus:block w-1/4">
              <Sidebar />
            </div>

            {/* Page content */}
            {/* <div className="flex-1">
              {children}
            </div> */}

            {/* Dynamic area(mobile footer will handle tabbing) */}
            <MobileFooter>
              <div className='w-full h-full'>
                {children}
              </div>
            </MobileFooter>

            {/* News (desktop only) */}
            <div className="hidden mdplus:block">
              <News />
            </div>
          </section>
        </main>
      </body>
    </html>
  )
}
